eureka:
  client:
    fetch-register-true: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      
okta:
  oauth2:
    issuer: https://dev-35621605.okta.com/oauth2/default
    audience: api://default
